# Generated by Django 4.2.8 on 2023-12-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
    ]
