# Generated by Django 4.2.8 on 2023-12-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('subscription', '0003_remove_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='payments.payments', verbose_name='платеж'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активность подписки'),
        ),
    ]
