# Generated by Django 4.2.8 on 2023-12-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('subscription', '0004_subscription_payments_alter_subscription_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payments', verbose_name='платеж'),
        ),
    ]
