# Generated by Django 4.2.8 on 2023-12-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('subscription', '0006_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payments', verbose_name='платеж'),
        ),
    ]
