# Generated by Django 4.2.8 on 2023-12-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='наименование статьи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/', verbose_name='изображение')),
                ('paid', models.BooleanField(default=False, verbose_name='бесплатная/платная публикация')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('date_change', models.DateField(auto_now=True, verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
