# Generated by Django 4.2.8 on 2023-12-20 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_publication_is_publication_publication_number_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='owner_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='владелец статьи'),
        ),
    ]
