# Generated by Django 4.2.8 on 2023-12-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_publication_owner_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='price',
        ),
    ]
