# Generated by Django 4.2.8 on 2023-12-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_publication_paid_remove_publication_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='бесплатная/платная публикация'),
        ),
        migrations.AddField(
            model_name='publication',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='стоимость подписки'),
        ),
    ]
