# Generated by Django 4.2.8 on 2023-12-21 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_publication_paid_publication_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='owner_publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор статьи'),
        ),
    ]
